config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/top', to: 'products#best_selling', as: :top_selling
  get '/top/t/*id/', to: 'products#best_selling', as: :top_selling_taxon

  get 'merchants/apply', to: 'home#sell', as: :sell_apply
  get 'merchants/apply/confirm', to: 'home#sell_apply_confirm'
end

Spree::Core::Engine.add_routes do
  get '/early-access', to: redirect('/signup')

  namespace :admin, path: Spree.admin_path do
    post '/sales' => 'orders#sales_report', :as => :sales_report
    post '/reassign_item/:line_item_id', to: 'orders#reassign_item', as: :reassign_item

    resources :product_collections, except: :show
    resources :product_collection_products, only: :destroy
    resources :user_rewards, only: :index

    resources :leads do
      collection do
        get :export
        post 'upload', to: 'leads#upload'
      end
    end

    resources :stock_locations do
      member do
        post :reindex
      end
    end

    resources :taxons do
      member do
        post :reindex, to: 'taxons#reindex'
      end
    end
  end

  scope :account do
    get '/(:tab)', to: 'users#show', tab: /orders/, as: :account

    get '/shipping', to: 'addresses#index', as: :user_addresses
    get '/shipping/edit', to: 'addresses#new', as: :new_address

    get '/password', to: redirect('/account/edit') # fix 404 on page refresh after password change fail

    get '/payment', to: 'credit_cards#index', as: :user_payment_methods
    get '/payment/edit', to: 'credit_cards#new', as: :new_payment_method

    resources :credit_cards, except: %i[index show new]

    resources :rewards, only: %i[index]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/inventory/fetch', to: 'inventory#fetch'
      get '/orders/fetch', to: 'orders#fetch'
      post '/orders/update', to: 'orders#update_items'
      put '/shipments/:id/cancel_item', to: 'shipments#cancel_item'
      put '/shipments/:id/confirm_item', to: 'shipments#confirm_item'
      post '/leads/wh', to: 'leads#wh'
    end
  end

  scope :orders do
    get '/:id/rate/:shipment_id', to: 'orders#rate_shipment', as: :rate_shipment
    post '/:id/rate/:shipment_id', to: 'orders#update_shipment_rate', as: :update_shipment_rate
  end

  scope :products do
    get '/:id/variations/(:variation)', to: 'products#similar_variants', as: :similar_variants
  end

  get '/c/:id', to: 'product_collections#show', as: :product_collections

  get '/taxons/mobile_menu_childs', to: 'taxons#mobile_menu_childs'

  get '/how-it-works', to: 'pages#how_it_works', as: :how_it_works

  post '/leads/subscribe', to: 'leads#subscribe'

  resources :addresses, except: %i[index show new]
end

Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  mount Spree::Core::Engine, at: '/'

  scope :freshdesk do
    get '/', to: 'freshdesk#login', as: :freshdesk
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :spree_user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq'
    mount PgHero::Engine, at: 'pghero'
    mount Ckeditor::Engine, at: 'ckeditor'
  end

  resources :api_docs, path: 'apidocs', only: [:index] do
    collection do
      get :schema
    end
  end
end

app/models/spree/orders/vendor_view.rb
module Spree
  module Orders
    class VendorView
      attr_accessor :order, :vendor

      def initialize(order, vendor)
        @order = order
        @vendor = vendor
      end

      include NumberAsParam

      delegate :payments, :state, :checkout_steps, :completed?, :payment_state,
               :completed_at, :approved?, :canceled?, :approved_at, :canceled_at,
               :canceler, :approver, :billing_address, :refresh_shipment_rates,
               :number, :errors, :considered_risky?, :special_instructions,
               :adjustments, :bill_address, :ship_address, :user, :model_name,
               :to_key, :cart?, :user_id, :outstanding_balance?, :outstanding_balance,
               :display_outstanding_balance, :email, :shipping_address, :hash_id, :channel,
               :shipping_eq_billing_address?, :is_risky?,
               to: :order

      extend Spree::DisplayMoney
      money_methods :item_total, :ship_total, :included_tax_total, :additional_tax_total,
                    :adjustment_total, :total

      def line_items
        order.line_items.joins(:variant).where(spree_variants: { vendor_id: @vendor })
      end

      def payment_transfers
        order.payment_transfers.where(vendor_id: @vendor)
      end

      def refunds
        order.refunds.joins(:payment_transfer).where(spree_payment_transfers: { vendor_id: @vendor })
      end

      def line_item_adjustments
        order.line_item_adjustments
             .joins('inner join spree_variants on spree_line_items.variant_id = spree_variants.id')
             .where(spree_variants: { vendor_id: @vendor })
      end

      def shipments
        order.shipments.joins(:stock_location).where(spree_stock_locations: { vendor_id: @vendor })
      end

      def shipment_adjustments
        order.shipment_adjustments
             .joins('inner join spree_stock_locations on spree_shipments.stock_location_id = spree_stock_locations.id')
             .where(spree_stock_locations: { vendor_id: @vendor })
      end

      def item_total
        line_items.sum('price * quantity')
      end

      def ship_total
        shipments.sum(:cost)
      end

      def included_tax_total
        line_items.sum(:included_tax_total) + shipments.sum(:included_tax_total)
      end

      def additional_tax_total
        line_items.sum(:additional_tax_total) + shipments.sum(:additional_tax_total)
      end

      def adjustment_total
        line_items.sum(:adjustment_total) + shipments.sum(:adjustment_total)
      end

      def total
        item_total + ship_total + adjustment_total
      end

      def shipment_state
        shipments.first.state
      end

      def total_rewards_amount
        @total_rewards_amount ||= line_items.sum(&:rewards_amount) + shipments.sum(&:cost_rewards_amount)
      end

      def rewards_amount
        vendor_rewards = 1 - vendor.subsidized_rewards / vendor.final_rewards
        total_rewards_amount * vendor_rewards
      end

      def subsidized_rewards
        total_rewards_amount - rewards_amount
      end

      def stripe_fee
        payment_transfers.sum(:fee)
      end

      def transfer_amount
        payment_transfers.sum(:amount)
      end

      def refunded_amount
        order.refunds.sum(:amount)
      end
    end
  end
end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
  before_action :load_vendor_view

  private

  def load_vendor_view
    @order = Spree::Orders::VendorView.new(@order, current_spree_vendor) if current_spree_vendor
  end
end

app/views/spree/admin/orders/_shipment_manifest.html.slim
- shipment.manifest.each do |item|
  tr.stock-item data-item-quantity="#{item.quantity}"
    td.item-image.image.text-center
      = mini_image(item.variant)
    td.item-name
      h4 = item.variant.product.name
      .small = variant_options(item.variant) unless item.variant.option_values.empty?
      - if item.variant.sku.present?
        .small #{Spree.t(:sku)}: #{item.variant.sku}
    td.item-price.text-center= item.line_item.single_money.to_html
    td.item-qty-show.text-center
      - item.states.each do |state,count|
        = count
        | x #{Spree.t(state).downcase}
        br
    - unless shipment.shipped?
      td.item-qty-edit.is-hidden
        = number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5
    td.item-total.text-center
      = line_item_shipment_price(item.line_item, item.line_item.quantity)
      .text-rewards = t('products.in_rewards', rewards: item.line_item.rewards_amount)
    td.cart-item-delete.actions.actions-3.text-center data-hook="cart_item_delete"
      - if !shipment.shipped? && !shipment.canceled? && can?(:update, item.line_item)
        / = link_to_with_icon 'pencil', Spree.t('actions.edit'), "#", class: 'edit-item btn btn-default btn-sm', title: Spree.t('actions.edit'), no_text: true
        = link_to_with_icon 'cancel', Spree.t('actions.cancel'), "#", class: 'cancel-item  btn btn-primary btn-sm', data: { action: 'cancel' }, title: Spree.t('actions.cancel'), style: 'display: none', no_text: true
        '
        = link_to_with_icon 'ok', Spree.t('actions.save'), "#", class: 'save-item btn btn-success btn-sm', data: {'shipment-number' => shipment.number, 'variant-id' => item.variant.id, action: 'save'}, title: Spree.t('actions.save'), style: 'display: none', no_text: true
        - if item.line_item.inventory_units.select(&:ordered?).any?
          = link_to Spree.t('confirm_shipment'), "#", class: 'confirm btn btn-block btn-primary btn-sm', data: {action: 'confirm_item'}, title: Spree.t('confirm_shipment')
          = link_to Spree.t('cancel_shipment'), "#", class: 'cancel btn btn-block btn-danger btn-sm', data: {action: 'cancel_item'}, title: Spree.t('cancel_shipment')
          = link_to Spree.t('split_shipment'), "#", class: 'split-item btn btn-block btn-default btn-sm', data: {action: 'split', 'variant-id' => item.variant.id}, title: Spree.t('split_shipment')
          - if current_spree_user.admin? && !shipment.stock_location.vendor.public_market?
            = link_to Spree.t('reassign_item'), admin_reassign_item_path(item.line_item), class: 'btn btn-block btn-warning btn-sm', data: { confirm: 'Are you sure?', method: 'post' }
        / = link_to_with_icon 'delete', Spree.t('delete'), "#", class: 'delete-item btn btn-danger btn-sm', data: { 'shipment-number' => shipment.number, 'variant-id' => item.variant.id, action: 'remove'}, title: Spree.t('delete'), no_text: true