config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/top', to: 'products#best_selling', as: :top_selling
  get '/top/t/*id/', to: 'products#best_selling', as: :top_selling_taxon

  get 'merchants/apply', to: 'home#sell', as: :sell_apply
  get 'merchants/apply/confirm', to: 'home#sell_apply_confirm'
end

Spree::Core::Engine.add_routes do
  get '/early-access', to: redirect('/signup')

  namespace :admin, path: Spree.admin_path do
    post '/sales' => 'orders#sales_report', :as => :sales_report
    post '/reassign_item/:line_item_id', to: 'orders#reassign_item', as: :reassign_item

    resources :product_collections, except: :show
    resources :product_collection_products, only: :destroy
    resources :user_rewards, only: :index

    resources :leads do
      collection do
        get :export
        post 'upload', to: 'leads#upload'
      end
    end

    resources :stock_locations do
      member do
        post :reindex
      end
    end

    resources :taxons do
      member do
        post :reindex, to: 'taxons#reindex'
      end
    end
  end

  scope :account do
    get '/(:tab)', to: 'users#show', tab: /orders/, as: :account

    get '/shipping', to: 'addresses#index', as: :user_addresses
    get '/shipping/edit', to: 'addresses#new', as: :new_address

    get '/password', to: redirect('/account/edit') # fix 404 on page refresh after password change fail

    get '/payment', to: 'credit_cards#index', as: :user_payment_methods
    get '/payment/edit', to: 'credit_cards#new', as: :new_payment_method

    resources :credit_cards, except: %i[index show new]

    resources :rewards, only: %i[index]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/inventory/fetch', to: 'inventory#fetch'
      get '/orders/fetch', to: 'orders#fetch'
      post '/orders/update', to: 'orders#update_items'
      put '/shipments/:id/cancel_item', to: 'shipments#cancel_item'
      put '/shipments/:id/confirm_item', to: 'shipments#confirm_item'
      post '/leads/wh', to: 'leads#wh'
    end
  end

  scope :orders do
    get '/:id/rate/:shipment_id', to: 'orders#rate_shipment', as: :rate_shipment
    post '/:id/rate/:shipment_id', to: 'orders#update_shipment_rate', as: :update_shipment_rate
  end

  scope :products do
    get '/:id/variations/(:variation)', to: 'products#similar_variants', as: :similar_variants
  end

  get '/c/:id', to: 'product_collections#show', as: :product_collections

  get '/taxons/mobile_menu_childs', to: 'taxons#mobile_menu_childs'

  get '/how-it-works', to: 'pages#how_it_works', as: :how_it_works

  post '/leads/subscribe', to: 'leads#subscribe'

  resources :addresses, except: %i[index show new]
end

Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  mount Spree::Core::Engine, at: '/'

  scope :freshdesk do
    get '/', to: 'freshdesk#login', as: :freshdesk
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :spree_user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq'
    mount PgHero::Engine, at: 'pghero'
    mount Ckeditor::Engine, at: 'ckeditor'
  end

  resources :api_docs, path: 'apidocs', only: [:index] do
    collection do
      get :schema
    end
  end
end

app/models/concerns/spree/normalize_blank_values.rb
module Spree
  module NormalizeBlankValues
    extend ActiveSupport::Concern

    included do
      before_validation :normalize_blank_values
    end

    def normalize_blank_values
      attributes.each do |column, _value|
        self[column].present? || self[column] = nil
      end
    end
  end
end

app/models/concerns/spree/product_kind.rb
module Spree
  module ProductKind
    extend ActiveSupport::Concern

    delegate :subtitle, :subtitle_presentation, :image_aspect_ratio, :additional_properties,
             :products_by_subtitle, :author_property_name, :product_description, :product_date,
             :additional_product_kind_name, :variation_property_name,
             :subtitle_property_name, :available_variations,
             to: :product_kind, allow_nil: true

    def product_kind_name
      @product_kind_name ||= taxonomy&.name&.downcase
    end

    def product_kind
      return @product_kind if @product_kind || product_kind_name.blank?

      kind_class = ProductKinds.const_get(product_kind_name.parameterize(separator: '_').camelize)
      @product_kind = kind_class.new(self)
    rescue NameError
      @product_kind = ProductKinds::Base.new(self)
    end

    def variation_property_value
      @variation_property_value ||= property(variation_property_name)
    end

    def variation_formatter
      @variation_formatter ||= variation_module.const_get('VariationFormatter').new(self)
    end

    def variation_module
      taxonomy ? taxonomy.variation_module : PublicMarket::Variations
    end

    def orderable?
      product_kind ? product_kind.orderable? : true
    end
  end
end

app/models/concerns/spree/stripe_customer.rb
module Spree
  module StripeCustomer
    extend ActiveSupport::Concern

    included do
      after_validation :create_stripe_customer, on: %i[create update], if: :update_stripe_customer?
      after_validation :update_stripe_card, on: :update, if: -> { valid_stripe_card? && has_payment_profile? }
    end

    def valid_stripe_card?
      errors.empty? && stripe_card?
    end

    def stripe_card?
      payment_method.method_type == 'stripe'
    end

    private

    def create_stripe_customer # rubocop:disable Metrics/AbcSize
      options = {
        email: user.email,
        login: payment_method.preferred_secret_key,
        address: stripe_bill_address
      }

      source = stripe_update_source
      creditcard = source.gateway_payment_profile_id || source

      response = provider.store(creditcard, options)

      if response.success?
        cc_type = source.cc_type
        response_cc_type = response.params['sources']['data'].first['brand']
        cc_type = payment_method.class::CARD_TYPE_MAPPING[response_cc_type] if payment_method.class::CARD_TYPE_MAPPING.include?(response_cc_type)

        self.cc_type = cc_type
        self.gateway_customer_profile_id = response.params['id']
        self.gateway_payment_profile_id = response.params['default_source'] || response.params['default_card']
      else
        errors.add(:base, stripe_gateway_error(response.message))
      end
    end

    def update_stripe_customer?
      valid_stripe_card? && (!gateway_customer_profile_id || gateway_payment_profile_id&.starts_with?('tok_'))
    end

    def update_stripe_card
      response = provider.update(gateway_customer_profile_id, gateway_payment_profile_id, card_to_options)
      errors.add(:base, stripe_gateway_error(response.message)) unless response.success?
    end

    def stripe_update_source
      self.cc_type = payment_method.class::CARD_TYPE_MAPPING[cc_type] if payment_method.class::CARD_TYPE_MAPPING.include?(cc_type)
      self
    end

    def stripe_gateway_error(error)
      if error.is_a?(ActiveMerchant::Billing::Response)
        error.params['message'] || error.params['response_reason_text'] || error.message
      else
        error.to_s
      end
    end

    def stripe_bill_address
      options = {
        address1: address.address1,
        address2: address.address2,
        city: address.city,
        zip: address.zipcode
      }

      if (country = address.country)
        options[:country] = country.name
      end

      if (state = address.state)
        options[:state] = state.name
      end

      options
    end

    def card_to_options
      {
        exp_month: month,
        exp_year: year,
        name: name,
        address_city: address.city,
        address_country: address.country.iso,
        address_state: address.state.abbr,
        address_line1: address.address1,
        address_line2: address.address2,
        address_zip: address.zipcode
      }
    end
  end
end

app/models/spree/address_decorator.rb
module Spree
  module AddressDecorator
    EXCLUDED_KEYS_FOR_COMPARISION = %w[id user_id updated_at created_at].freeze
    MAX_NICKNAME_LENGTH = 25

    def self.prepended(base)
      base.acts_as_paranoid

      base.belongs_to :user, class_name: Spree.user_class.to_s, optional: true, inverse_of: :addresses

      base.phony_normalize :phone, default_country_code: 'US'
      base.validates :phone, phony_plausible: true
      base.validates :title, length: { maximum: MAX_NICKNAME_LENGTH }, allow_blank: true

      base.after_save :ensure_one_default
    end

    def same_as?(other)
      return false if other.nil?

      attributes.except(*EXCLUDED_KEYS_FOR_COMPARISION) == other.attributes.except(*EXCLUDED_KEYS_FOR_COMPARISION)
    end

    def full_address
      [address1, city, "#{state.abbr} #{zipcode}", country].join(', ')
    end

    private

    def ensure_one_default
      return if user_id.blank? || !default

      Spree::Address.where(default: true, user_id: user_id)
                    .where.not(id: id)
                    .update_all(default: false) # rubocop:disable Rails/SkipsModelValidations
    end
  end

  Address.prepend(AddressDecorator)
end

app/models/spree/calculator/shipping/flexi_order_rate.rb
require_dependency 'spree/shipping_calculator'

module Spree
  module Calculator::Shipping
    class FlexiOrderRate < ShippingCalculator
      preference :first_item,      :decimal, default: 0.0
      preference :additional_item, :decimal, default: 0.0
      preference :max_items,       :integer, default: 0
      preference :currency,        :string,  default: -> { Spree::Config[:currency] }

      def self.description
        Spree.t(:shipping_flexible_order_rate)
      end

      def compute_package(package)
        quantity = package.contents.sum(&:quantity)

        if quantity.positive? && last_order_shipment?(package.contents.first.inventory_unit)
          flexi_rate_calculator.compute_from_quantity(quantity)
        else
          preferred_additional_item * quantity
        end
      end

      private

      def last_order_shipment?(unit)
        return true if unit.order.blank? # can be blank for fake packages

        unit.order.shipments
            .joins(:stock_location, shipping_methods: :calculator)
            .where.not(state: :canceled)
            .where(spree_calculators: { id: id })
            .where(spree_stock_locations: { vendor_id: unit.variant.vendor_id })
            .where('spree_shipments.id > ?', unit.shipment_id)
            .blank?
      end

      def flexi_rate_calculator
        ::Spree::Calculator::FlexiRate.new(
          preferred_additional_item: preferred_additional_item,
          preferred_first_item: preferred_first_item,
          preferred_max_items: preferred_max_items,
          preferred_currency: preferred_currency
        )
      end
    end
  end
end

app/models/spree/classification_decorator.rb
module Spree
  module ClassificationDecorator
    def self.prepended(base)
      # base.after_create_commit :notify_uncategorized, if: -> { taxon.name == Spree::Taxon::UNCATEGORIZED_NAME }
    end

    def notify_uncategorized
      PublicMarket::Workers::Slack::DataReconciliationWorker.perform_async(product_id: product_id, message_type: 'uncategorized')
    rescue => e # rubocop:disable Style/RescueStandardError
      Rails.env.production? || Rails.env.staging? ? Raven.capture_exception(e) : raise(e)
    end
  end

  Classification.prepend(ClassificationDecorator)
end

app/models/spree/credit_card_decorator.rb
module Spree
  module CreditCardDecorator
    MAX_NICKNAME_LENGTH = 25

    def self.prepended(base)
      base.include(Spree::StripeCustomer)
      base.extend(Enumerize)
      base.extend(FriendlyId)

      base.friendly_id :slug_candidates, use: %i[slugged scoped], scope: :user

      base.acts_as_paranoid

      base.belongs_to :address, class_name: 'Spree::Address', required: true, dependent: :destroy
      base.accepts_nested_attributes_for :address

      base.validates :month, :year, numericality: { only_integer: true }
      base.validates :name, length: { maximum: MAX_NICKNAME_LENGTH }, allow_blank: true

      base.before_validation :clone_shipping_address, if: :use_shipping?

      # use enumerize instead of simple enum, because using enum lead to error in class_eval https://github.com/spree/spree/issues/5786
      base.enumerize :funding, in: { credit: 0, debit: 1, unknown: 2, prepaid: 3 }, default: :credit, predicates: { prefix: true }

      base.delegate :provider, to: :payment_method

      base.attr_accessor :use_shipping
    end

    def expiry=(expiry)
      self[:month], self[:year] =
        if expiry.match?(%r{\d{2}\s?\/\s?\d{2,4}}) # will match mm/yy and mm / yyyy
          expiry.delete(' ').split('/')
        elsif (match = expiry.match(/(\d{2})(\d{2,4})/)) # will match mmyy and mmyyyy
          [match[1], match[2]]
        end

      if self[:year]
        self[:year] = "20#{self[:year]}" if (self[:year] / 100).zero?
        self[:year] = self[:year].to_i
      end

      self[:month] = self[:month].to_i if self[:month]
    end

    def display_number(show_prefix: false)
      return '' unless last_digits

      prefix =
        case show_prefix
        when false
          nil
        when :short
          'x'
        else
          'XXXX-XXXX-XXXX'
        end

      "#{prefix}-#{last_digits}"
    end

    def name_with_initial
      first_name, last_name = name.split(' ')
      "#{first_name} #{last_name&.first}."
    end

    def use_shipping?
      use_shipping.present?
    end

    private

    def clone_shipping_address
      if (user_address = user.addresses.find_by(id: use_shipping)).present?
        if address.blank?
          self.address = user_address.clone
        else
          address.attributes = user_address.attributes.except('id', 'updated_at', 'created_at')
        end
      end

      address.user_id = nil
    end

    def slug_candidates
      [
        :card_name,
        [:card_name, -> { SecureRandom.uuid.first(5) }]
      ]
    end
  end

  CreditCard.prepend(CreditCardDecorator)
end

app/models/spree/fulfilment_changer_decorator.rb
Spree::FulfilmentChanger.class_eval do
  def initialize(params = {})
    @current_stock_location = params[:current_stock_location]
    @desired_stock_location = params[:desired_stock_location]
    @current_shipment       = params[:current_shipment]
    @desired_shipment       = params[:desired_shipment]
    @variant                = params[:variant]
    @quantity               = params[:quantity]
    @available_quantity     = [
      desired_stock_location.try(:count_on_hand, variant).to_i,
      @quantity
    ].max

    @desired_shipment.rewards = @current_shipment.rewards
  end
end

app/models/spree/gateway/stripe_gateway_decorator.rb
Spree::Gateway::StripeGateway.class_eval do
  def transfer(money, source_transaction, destination, gateway_options)
    options = {
      currency: gateway_options[:currency],
      source_transaction: source_transaction,
      destination: destination
    }

    provider.transfer(money, options)
  end

  def fee(payment)
    payment.amount * 0.029 + 0.3
  end

  def reverse_transfer(money, transfer_id)
    provider.reverse_transfer(money, transfer_id: transfer_id)
  end

  def options_for_purchase_or_auth(money, creditcard, gateway_options)
    options = {}
    options[:description] = Spree.t('payment_description', order_id: gateway_options[:order_id])
    options[:currency] = gateway_options[:currency]

    if (customer = creditcard.gateway_customer_profile_id)
      options[:customer] = customer
    end

    if (token_or_card_id = creditcard.gateway_payment_profile_id)
      creditcard = token_or_card_id
    end

    [money, creditcard, options]
  end
end

ActiveMerchant::Billing::StripeGateway.class_eval do
  def transfer(money, options)
    post = {
      source_transaction: options[:source_transaction],
      destination: options[:destination]
    }
    add_amount(post, money, options, true)

    commit(:post, 'transfers', post, {})
  end

  def reverse_transfer(money, options)
    post = { amount: money }

    commit(:post, "transfers/#{CGI.escape(options[:transfer_id])}/reversals", post, {})
  end
end

app/models/spree/image_decorator.rb
Spree::Image.class_eval do
  do_not_validate_attachment_file_type :attachment

  process_in_background :attachment

  _validators[:attachment].reject! { |validator| validator.is_a?(Paperclip::Validators::AttachmentContentTypeValidator) }
  _validate_callbacks.each do |callback|
    callback.raw_filter.attributes.delete(:attachment) if callback.raw_filter.is_a?(Paperclip::Validators::AttachmentContentTypeValidator)
  end

  validates_attachment_content_type :attachment, content_type: %r{\Aimage\/.*\z}

  def self.accepted_image_types
    %w[image/jpeg image/jpg image/png image/x-png image/gif]
  end

  def find_dimensions
    temporary = attachment.queued_for_write[:original]
    return if temporary.blank?

    filename = temporary.path unless temporary.nil?
    filename = attachment.path if filename.blank?
    geometry = Paperclip::Geometry.from_file(filename)
    self.attachment_width  = geometry.width
    self.attachment_height = geometry.height
  end

  attachment_definitions[:attachment][:path] = Paperclip::Attachment.default_options[:path]
end

app/models/spree/lead.rb
module Spree
  class Lead < ApplicationRecord
    belongs_to :user, class_name: Spree.user_class.to_s, optional: true

    before_validation :normalize_email

    validates :email, presence: true

    # after_create :send_email

    private

    def send_email
      return if User.find_by(email: email).present?

      UserMailer.lead_whitelisted(id).deliver_later(wait: 1.minute)
    end

    def normalize_email
      email&.strip!
      email&.downcase!
    end
  end
end

app/views/spree/users/_account_menu.html.slim
- account_menu = capture do
  li.no-margin class=('active' if @account_tab == :summary)
    a.plain-link href='/account' = t('menus.account.summary')

  - links = %i[payment shipping orders rewards]
  - links.each do |link|
    li.no-margin class=('active' if @account_tab == link)
      a.plain-link href="/account/#{link}" = t("menus.account.#{link}")

ul.hidden-xs.nav.nav-pills.nav-stacked#account-menu
  = account_menu

.visible-xs.dropdown.user-account-menu-dropdown
  button.btn-block.btn-outlined data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' type='button'
    .flex.between.align-center
      = t("menus.account.#{@account_tab || :summary}")
      span.caret

  ul.dropdown-menu
    = account_menu

app/views/spree/users/_account_orders.html.slim
.account-my-orders data-hook='account_my_orders'
  h3.upcase.no-margin = t('users.orders-history.title')
  br
  - if @orders.present?
    = render partial: 'spree/orders/order', collection: @orders, as: :order
  - else
    .alert.alert-info= Spree.t(:you_have_no_orders_yet)

  .text-right = paginate @orders

  hr.margin-text-bottom
  = render 'shared/disclaimer', anchor: false

app/views/spree/users/_account_summary.html.slim
.account-summary
  h3.upcase.no-margin.text-center-xs = t('users.account-page.welcome', username: @user.display_name)

  - sections = %i[user_info referral_link user_balance address payment_info wallet]
  = render partial: 'spree/users/summary/template', collection: sections, as: :partial, spacer_template: 'spree/shared/hr_spacer'

app/views/spree/users/_account_template.html.slim
- @body_class = 'user-account-layout'

.row
  - if spree_user_signed_in?
    .col-sm-3.col-lg-offset-2.col-lg-2
      = render 'spree/users/account_menu'

  .account-pages--content  class=(spree_user_signed_in? ? 'col-sm-9 col-lg-6' : 'col-md-6 col-md-offset-3')
    = yield

app/views/spree/users/_confirm_alert.html.slim
.alert-confirm-email.text-center
  p.info-icon-left.outline-info
    == t('account.confirm_alert', email: spree_current_user.unconfirmed_email || spree_current_user.email)

  = link_to(t('users.send_verification'), spree_user_confirmation_path, method: :post, class: 'btn btn-outlined-white')
  span.margin-text-horizont-eq or
  = link_to(t('users.change_email'), edit_account_path, class: 'white-link')

app/views/spree/users/_delete_account_modal.html.slim
.modal.modal-wide-paddings.modal-vertical-center.fade#delete-account-modal tabindex='-1' role='dialog'
  .modal-dialog
    .modal-content
      .modal-header
        button type='button' class='close' data-dismiss='modal' aria-label='Close'
          span aria-hidden='true' &times;

        h5.upcase.modal-title.text-black = t('users.delete-account')

      .modal-body.text-center
        br
        .text-dark-danger = t('users.delete-account-prompt')
        br
        br

        .row
          .col-xs-12.col-md-6
            button.btn.btn-white.btn-block data-dismiss='modal' aria-label='Close' = Spree.t('cancel')
          .col-xs-12.col-md-6
            = link_to t('users.confirm-deletion'), account_path, method: :delete, class: 'btn btn-danger', data: { turbolinks: false }

app/views/spree/users/_form.html.slim
- verified = @user.confirmed?
= simple_form_for @user, url: spree.user_path(id: @user.id), remote: true, method: :put, wrapper: :vertical_hint_label, html: { id: 'edit_user_info', class: 'user-edit-form leave-check' } do |f|
  - if verified
    = render 'reconfirm_email_modal'

  .flex
    = f.input :first_name, input_html: { value: f.object.first_name.presence }, wrapper_html: { class: 'flex-grow-1 margin-text-right' }
    = f.input :last_name, input_html: { value: f.object.last_name.presence }, wrapper_html: { class: 'flex-grow-1 margin-text-left' }

  = f.input :email, label: false, error: f.object.errors[:email].first&.html_safe, wrapper_html: { class: ('form-group-valid' if session.delete(:hightlight_email)) }
    - correct_email = @user.errors[:email].blank?

    div
      = f.input_field :email, value: f.object.email.presence, class: "form-control input-lg", data: { 'old-email': f.object.email }
      = f.label :email

      - if correct_email
        .user_email--addition-wrapper.flex.align-center
          - if verified
            .text-small.text-success.check-left.condensed = t('devise.verified_email')
          - else
            = link_to(t('devise.send_confirmation_email'), spree_user_confirmation_path, method: :post)

    - if verified && correct_email
      span.text-small.feedback-hint = t('users.account-page.change-email-verification')

  = f.input :login, label: false, required: false, error: f.object.errors[:login].first
    div
      = f.input_field :login, value: f.object.login.presence, class: "form-control input-lg"
      = f.label :login

    - if @user.errors.blank?
      span.text-small.feedback-hint = t('users.account-page.username-hint')

  = f.input :password_mask, label: false
    div
      = f.input_field :password_mask, type: :text, value: '**************', disabled: true, class: "form-control input-lg"
      = f.label :password

      .user_password--addition-wrapper.flex.align-center
        = link_to(t('devise.send_reset_password_email'), spree.reset_password_path, method: :post)

  = f.submit 'Save', class: 'btn btn-block btn-primary'

app/views/spree/users/_reconfirm_email_modal.html.slim
.modal.modal-wide-paddings.modal-vertical-center.fade#reconfirm-email-modal tabindex='-1' role='dialog'
  .modal-dialog
    .modal-content
      .modal-header
        button type='button' class='close' data-dismiss='modal' aria-label='Close'
          span aria-hidden='true' &times;

        h5.upcase.modal-title.text-black= t('users.reconfirm-email.head')

      .modal-body.text-center
        br
        .text-warning = t('users.reconfirm-email.text')
        br
        br

        .row
          .col-xs-12.col-md-6
            button.btn.btn-white.btn-block data-dismiss='modal' aria-label='Close' type='button' = Spree.t('cancel')
          .col-xs-12.col-md-6
            button.btn.btn-warning.btn-block#reconfirm-email-btn data-dismiss='modal' type='button' = t('users.reconfirm-email.button')

app/views/spree/users/edit.html.slim
= render layout: 'spree/users/account_template'
  .user-account-form
    = render partial: 'spree/shared/account_breadcrumbs', locals: { items: [link_to(Spree.t(:your_account), account_path), Spree.t(:editing_user)] }

    h3.upcase.no-margin.text-color = Spree.t(:editing_user)

    br

    = render partial: 'spree/users/form'

    = render 'delete_account_modal'

    .text-right.user-delete-btn-wrapper
      button.btn.btn-link data-toggle='modal' data-target='#delete-account-modal'
        = image_tag 'icons/trash.svg'
        small = t('users.delete-account')

app/views/spree/users/show.html.slim
= render layout: 'spree/users/account_template'
  = render partial: "account_#{@account_tab}"

app/views/spree/users/update.js.erb
<%= render partial: 'spree/shared/flash_messages' %>

$('.user-edit-form').html("<%= j(render(partial: 'spree/users/form')) %>")

<% if @user.valid? %>
  <% @user.saved_changes.keys.reject { |key| %w[updated_at].include?(key) }.each do |k, v| %>
    var input = $("input[name='user[" + "<%= k %>" + "]']")
    input.parents('.form-group').addClass('form-group-valid')
  <% end %>
<% end %>