config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/top', to: 'products#best_selling', as: :top_selling
  get '/top/t/*id/', to: 'products#best_selling', as: :top_selling_taxon

  get 'merchants/apply', to: 'home#sell', as: :sell_apply
  get 'merchants/apply/confirm', to: 'home#sell_apply_confirm'
end

Spree::Core::Engine.add_routes do
  get '/early-access', to: redirect('/signup')

  namespace :admin, path: Spree.admin_path do
    post '/sales' => 'orders#sales_report', :as => :sales_report
    post '/reassign_item/:line_item_id', to: 'orders#reassign_item', as: :reassign_item

    resources :product_collections, except: :show
    resources :product_collection_products, only: :destroy
    resources :user_rewards, only: :index

    resources :leads do
      collection do
        get :export
        post 'upload', to: 'leads#upload'
      end
    end

    resources :stock_locations do
      member do
        post :reindex
      end
    end

    resources :taxons do
      member do
        post :reindex, to: 'taxons#reindex'
      end
    end
  end

  scope :account do
    get '/(:tab)', to: 'users#show', tab: /orders/, as: :account

    get '/shipping', to: 'addresses#index', as: :user_addresses
    get '/shipping/edit', to: 'addresses#new', as: :new_address

    get '/password', to: redirect('/account/edit') # fix 404 on page refresh after password change fail

    get '/payment', to: 'credit_cards#index', as: :user_payment_methods
    get '/payment/edit', to: 'credit_cards#new', as: :new_payment_method

    resources :credit_cards, except: %i[index show new]

    resources :rewards, only: %i[index]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/inventory/fetch', to: 'inventory#fetch'
      get '/orders/fetch', to: 'orders#fetch'
      post '/orders/update', to: 'orders#update_items'
      put '/shipments/:id/cancel_item', to: 'shipments#cancel_item'
      put '/shipments/:id/confirm_item', to: 'shipments#confirm_item'
      post '/leads/wh', to: 'leads#wh'
    end
  end

  scope :orders do
    get '/:id/rate/:shipment_id', to: 'orders#rate_shipment', as: :rate_shipment
    post '/:id/rate/:shipment_id', to: 'orders#update_shipment_rate', as: :update_shipment_rate
  end

  scope :products do
    get '/:id/variations/(:variation)', to: 'products#similar_variants', as: :similar_variants
  end

  get '/c/:id', to: 'product_collections#show', as: :product_collections

  get '/taxons/mobile_menu_childs', to: 'taxons#mobile_menu_childs'

  get '/how-it-works', to: 'pages#how_it_works', as: :how_it_works

  post '/leads/subscribe', to: 'leads#subscribe'

  resources :addresses, except: %i[index show new]
end

Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  mount Spree::Core::Engine, at: '/'

  scope :freshdesk do
    get '/', to: 'freshdesk#login', as: :freshdesk
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :spree_user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq'
    mount PgHero::Engine, at: 'pghero'
    mount Ckeditor::Engine, at: 'ckeditor'
  end

  resources :api_docs, path: 'apidocs', only: [:index] do
    collection do
      get :schema
    end
  end
end

app/models/spree/lead.rb
module Spree
  class Lead < ApplicationRecord
    belongs_to :user, class_name: Spree.user_class.to_s, optional: true

    before_validation :normalize_email

    validates :email, presence: true

    # after_create :send_email

    private

    def send_email
      return if User.find_by(email: email).present?

      UserMailer.lead_whitelisted(id).deliver_later(wait: 1.minute)
    end

    def normalize_email
      email&.strip!
      email&.downcase!
    end
  end
end

app/controllers/spree/admin/leads_controller.rb
module Spree
  module Admin
    class LeadsController < ResourceController
      def index
        respond_with(@collection)
      end

      def upload
        if params[:leads][:file].blank?
          flash[:error] = 'No file chosen'
          redirect_to new_admin_lead_path
        else
          Leads::Upload.call(params[:leads][:file], source: params[:leads][:source])
          flash[:success] = 'Successfully uploaded'
          redirect_to location_after_save
        end
      end

      def export
        send_data lead_csv, filename: "leads-#{Time.current.strftime('%d-%b-%Y')}.csv"
      end

      private

      def collection
        return @collection if @collection.present?

        params[:q] = {} if params[:q].blank?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_properties_per_page])
      end

      def lead_csv
        CSV.generate(headers: true) do |csv|
          csv << ['Lead ID', 'Email', 'User ID', 'First Name', 'Last Name']

          Lead.find_each do |lead|
            csv << [lead.id, lead.email, lead.user_id, lead.user&.first_name, lead.user&.last_name]
          end
        end
      end

      def upload_params
        params.require(:leads).permit(:source, :file)
      end
    end
  end
end

app/controllers/spree/api/v1/leads_controller.rb
module Spree
  module Api
    module V1
      class LeadsController < Spree::Api::BaseController
        def wh
          authorize!(:create, Spree::Lead)
          Leads::Push.call(params)
        end
      end
    end
  end
end

app/controllers/spree/leads_controller.rb
module Spree
  class LeadsController < Spree::BaseController
    def subscribe
      Leads::Push.call(params)

      head :ok
    end
  end
end

app/views/spree/admin/leads/_form.html.slim
.row
  .col-xs-12
    = f.field_container :email, class: ['form-group'] do
      = f.label :email, Spree.t(:email)
      span.required
        | *
      = f.text_field :email, class: 'form-control'
      = f.error_message_on :email

    = f.field_container :source, class: ['form-group'] do
      = f.label :source, :source
      = f.text_field :source, class: 'form-control'
      = f.error_message_on :source

    = f.field_container :source_id, class: ['form-group'] do
      = f.label :source_id, :source_id
      = f.text_field :source_id, class: 'form-control'
      = f.error_message_on :source_id

    = f.field_container :source_parent_id, class: ['form-group'] do
      = f.label :source_parent_id, :source_parent_id
      = f.text_field :source_parent_id, class: 'form-control'
      = f.error_message_on :source_parent_id

    = f.field_container :user, class: ['form-group'] do
      = f.label :user, Spree.t(:user)
      = f.select :user_id, [], { include_blank: true }, disabled: true, class: 'select2'

app/views/spree/admin/leads/edit.html.slim
- content_for :page_title do
  = link_to Spree.t(:lead), admin_leads_url
  ' &nbsp;/
  = @lead.email

= render partial: 'spree/admin/shared/error_messages', locals: { target: @lead }

= form_for [:admin, @lead], html: { multipart: true } do |f|
  fieldset
    = render partial: 'form', locals: { f: f }
    = render partial: 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/leads/index.html.slim
- content_for :page_title do
  = plural_resource_name(Spree::Lead)

- if can?(:create, Spree::Lead)
  - content_for :page_actions do
    = button_link_to Spree.t(:export_leads), export_admin_leads_url, class: "btn-primary", icon: 'export'
    '
    = button_link_to Spree.t(:new_lead), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_lead_collection_link'

- if @collection.any?
  - content_for :table_filter do
    = search_form_for [:admin, @search] do |f|
      .row
        .col-xs-12.col-md-6
          .form-group
            = f.label :email_cont, Spree.t(:email)
            = f.text_field :email_cont, class: "form-control js-quick-search-target js-filterable"

      .form-actions
        = button Spree.t(:search), 'search'

  table.table
    thead
      tr
        th
          = Spree.t(:email)
        th
          = Spree.t(:user)

        th.actions
    tbody
      - @collection.each do |lead|
        tr id=spree_dom_id(lead)
          td
            = lead.email
          td
            - if lead.user
              = link_to(lead.user.display_name, spree.admin_user_path(id: lead.user_id))
          td.actions.actions-2.text-right
            = link_to_with_icon('show', Spree.t(:show), spree.admin_lead_path(id: lead.id), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'show' }) if can?(:show, lead)
            | &nbsp;
            = link_to_edit(lead, no_text: true) if can?(:edit, lead)
            | &nbsp;
            = link_to_delete(lead, no_text: true) if can?(:delete, lead)
- else
  .alert.alert-info.no-objects-found
    = Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Lead))
    ' ,
    = link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Lead)

= paginate @collection

app/views/spree/admin/leads/new.html.slim
= render partial: 'spree/admin/shared/error_messages', locals: { target: @lead }

- content_for :page_title do
  = link_to Spree.t(:leads), admin_leads_url
  ' &nbsp;/
  = Spree.t(:new_lead)

= form_for [:admin, @lead], html: { multipart: true } do |f|
  fieldset
    = render partial: 'form', locals: { f: f }

    .form-actions
      = render partial: 'spree/admin/shared/new_resource_links'

h3 OR

= form_for(:leads, url: upload_admin_leads_path, method: :post, multipart: true) do |f|
  fieldset
    p.form-buttons
      = f.field_container :source, class: ['form-group'] do
        = f.label :source, :source
        = f.text_field :source, class: 'form-control'
        = f.error_message_on :source

      = f.field_container :file do
        = f.label :file, 'Upload file'

        br

        = f.file_field :file

      br

      = button 'Upload', 'add', 'submit', class: "btn-success"

app/views/spree/admin/leads/show.html.slim
- content_for :page_title do
  = link_to Spree.t(:lead), admin_leads_url
  ' &nbsp;/
  = @lead.email

h4 Referred Count: #{Spree::Lead.where("metadata ->> 'parent_email' = ?",  @lead.email).count}

p Email: #{@lead.email}
p Source Ref ID: #{@lead.source_id}
p Parent source Ref ID: #{@lead.source_parent_id}
p Source created: #{@lead.source_created_at}

- if (user = @lead.user)
  p User: #{link_to(user.display_name, spree.admin_user_path(id: user.id))}

p Metadata:
- @lead.metadata.each do |k, v|
  strong> = k
  = v
  br