config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/top', to: 'products#best_selling', as: :top_selling
  get '/top/t/*id/', to: 'products#best_selling', as: :top_selling_taxon

  get 'merchants/apply', to: 'home#sell', as: :sell_apply
  get 'merchants/apply/confirm', to: 'home#sell_apply_confirm'
end

Spree::Core::Engine.add_routes do
  get '/early-access', to: redirect('/signup')

  namespace :admin, path: Spree.admin_path do
    post '/sales' => 'orders#sales_report', :as => :sales_report
    post '/reassign_item/:line_item_id', to: 'orders#reassign_item', as: :reassign_item

    resources :product_collections, except: :show
    resources :product_collection_products, only: :destroy
    resources :user_rewards, only: :index

    resources :leads do
      collection do
        get :export
        post 'upload', to: 'leads#upload'
      end
    end

    resources :stock_locations do
      member do
        post :reindex
      end
    end

    resources :taxons do
      member do
        post :reindex, to: 'taxons#reindex'
      end
    end
  end

  scope :account do
    get '/(:tab)', to: 'users#show', tab: /orders/, as: :account

    get '/shipping', to: 'addresses#index', as: :user_addresses
    get '/shipping/edit', to: 'addresses#new', as: :new_address

    get '/password', to: redirect('/account/edit') # fix 404 on page refresh after password change fail

    get '/payment', to: 'credit_cards#index', as: :user_payment_methods
    get '/payment/edit', to: 'credit_cards#new', as: :new_payment_method

    resources :credit_cards, except: %i[index show new]

    resources :rewards, only: %i[index]
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      get '/inventory/fetch', to: 'inventory#fetch'
      get '/orders/fetch', to: 'orders#fetch'
      post '/orders/update', to: 'orders#update_items'
      put '/shipments/:id/cancel_item', to: 'shipments#cancel_item'
      put '/shipments/:id/confirm_item', to: 'shipments#confirm_item'
      post '/leads/wh', to: 'leads#wh'
    end
  end

  scope :orders do
    get '/:id/rate/:shipment_id', to: 'orders#rate_shipment', as: :rate_shipment
    post '/:id/rate/:shipment_id', to: 'orders#update_shipment_rate', as: :update_shipment_rate
  end

  scope :products do
    get '/:id/variations/(:variation)', to: 'products#similar_variants', as: :similar_variants
  end

  get '/c/:id', to: 'product_collections#show', as: :product_collections

  get '/taxons/mobile_menu_childs', to: 'taxons#mobile_menu_childs'

  get '/how-it-works', to: 'pages#how_it_works', as: :how_it_works

  post '/leads/subscribe', to: 'leads#subscribe'

  resources :addresses, except: %i[index show new]
end

Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  mount Spree::Core::Engine, at: '/'

  scope :freshdesk do
    get '/', to: 'freshdesk#login', as: :freshdesk
  end

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  authenticate :spree_user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: 'sidekiq'
    mount PgHero::Engine, at: 'pghero'
    mount Ckeditor::Engine, at: 'ckeditor'
  end

  resources :api_docs, path: 'apidocs', only: [:index] do
    collection do
      get :schema
    end
  end
end

app/models/spree/product_collection.rb
module Spree
  class ProductCollection < Spree::Base
    STAFF_PICKS_NAME = 'Staff Picks'.freeze

    has_many :product_collections_products, class_name: 'Spree::ProductCollectionProduct', dependent: :destroy
    has_many :products, through: :product_collections_products, class_name: 'Spree::Product', source: :product
    belongs_to :taxonomy, class_name: 'Spree::Taxonomy'

    has_one :image, as: :viewable, dependent: :destroy, class_name: 'Spree::ProductCollectionImage'

    belongs_to :user, class_name: 'Spree::User'

    scope :promoted, -> { where(promoted: true) }

    before_destroy :staff_picks?

    extend FriendlyId
    friendly_id :name, use: :slugged

    validates :name, presence: true

    def self.staff_picks
      find_by(name: STAFF_PICKS_NAME)
    end

    private

    def should_generate_new_friendly_id?
      slug.blank? || super
    end

    def staff_picks?
      return if name.casecmp(STAFF_PICKS_NAME) != 0

      errors.add(:base, I18n.t('activerecord.errors.models.spree/product_collection.staff_picks'))
      throw :abort
    end
  end
end

app/controllers/spree/admin/product_collections_controller.rb
module Spree
  module Admin
    class ProductCollectionsController < ResourceController
      custom_callback(:create).before(:build_image)
      custom_callback(:update).before(:build_image)

      def index
        respond_with(@collection)
      end

      def edit
        @product_collection_products =
          @object.product_collections_products
                 .includes(:product)
                 .page(params[:page])
                 .per(Spree::Config[:admin_properties_per_page])

        super
      end

      def destroy
        if @object.destroy
          flash[:success] = flash_message_for(@object, :successfully_removed)
          respond_with(@object) do |format|
            format.html { redirect_to location_after_destroy }
            format.js   { render_js_for_destroy }
          end
        else
          render plain: @object.errors.full_messages.join(', '), status: :unprocessable_entity
        end
      end

      private

      def build_image
        return if permitted_image_params[:image].blank?

        @object.build_image(attachment: permitted_image_params[:image])
      end

      def permitted_resource_params
        params.require(:product_collection).permit(:name, :slug, :influencer_slug, :description, :promoted, :taxonomy_id, :user_id)
      end

      def permitted_image_params
        params.require(:product_collection).permit(:image)
      end

      def find_resource
        ProductCollection.friendly.find(params[:id])
      end

      def collection
        return @collection if @collection.present?

        params[:q] = {} if params[:q].blank?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_properties_per_page])
      end

      def location_after_save
        spree.edit_admin_product_collection_url(@object)
      end
    end
  end
end

app/controllers/spree/product_collections_controller.rb
module Spree
  class ProductCollectionsController < Spree::StoreController
    include Spree::ProductsHelper
    helper_method :cache_key_for_product # not inclusion causes exception in product partial

    before_action :load_product_collection, only: [:show]
    before_action :set_influencer_cookie, only: [:show]

    after_action :add_vary_header, only: :show

    def show
      params[:filter] ||= {}
      params[:filter][:collections] = [@product_collection.id]

      @hide_taxon_breadcrumbs = true
      @taxon = @product_collection.taxonomy&.root
      @products = build_searcher(params).call

      self.title = @product_collection.name

      respond_to do |format|
        format.html { render 'spree/product_collections/show' }
        format.js { render 'spree/shared/search/products' }
      end
    end

    private

    def load_product_collection
      @product_collection = ProductCollection.find_by(slug: params[:id]) ||
                            ProductCollection.find_by(influencer_slug: params[:id])

      raise ActiveRecord::RecordNotFound, 'Record not found.' if @product_collection.blank?
    end

    def set_influencer_cookie
      return if @product_collection.influencer_slug != params[:id]

      cookies['_inf_src'] = @product_collection.influencer_slug if cookies['_inf_src'].blank?
      cookies['refuid'] = @product_collection&.user&.hash_id
    end
  end
end

app/helpers/spree/product_collections_helper.rb
module Spree
  module ProductCollectionsHelper
    ALLOWED_PROD_COLLECTION_DESCRIPTION_TAGS = %w[abbr acronym address b br cite em hr i li ol p span strike strong sub sup ul].freeze
    ALLOWED_PROD_COLLECTION_DESCRIPTION_ATTRS = %w[class].freeze

    def bio_length
      case device
      when :mobile
        130
      when :tablet
        300
      else
        900
      end
    end

    def product_collection_description(description)
      sanitize(description, tags: ALLOWED_PROD_COLLECTION_DESCRIPTION_TAGS, attributes: ALLOWED_PROD_COLLECTION_DESCRIPTION_ATTRS)
    end
  end
end

app/views/spree/admin/product_collections/_form.html.slim
.row
  .col-xs-12
    = f.field_container :name, class: ['form-group'] do
      = f.label :name, Spree.t(:name)
      span.required
        | *
      = f.text_field :name, class: 'form-control'
      = f.error_message_on :name

    = f.field_container :slug, class: ['form-group'] do
      = f.label :slug, Spree.t(:slug)
      = f.text_field :slug, class: 'form-control'
      = f.error_message_on :slug

    = f.field_container :influencer_slug, class: ['form-group'] do
      = f.label :influencer_slug
      = f.text_field :influencer_slug, class: 'form-control', id: 'permalink_part'
      = f.error_message_on :influencer_slug
      p class="help-block" id="permalink_part_display" #{spree.root_url}c/

    = f.field_container :description, class: ['form-group'] do
      = f.label :description, Spree.t(:description)
      = f.text_area :description, class: 'form-control'
      = f.error_message_on :description

    = f.field_container :image, class: ['form-group'] do
      = f.label :image, Spree.t(:image)
      = f.file_field :image

      - if f.object.image
        = image_tag f.object.image.url(:thumb)

    .checkbox
      = f.label :promoted do
        = f.check_box :promoted
        = Spree.t(:promoted)

    = f.field_container :taxonomy, class: ['form-group'] do
      = f.label :taxonomy, Spree.t(:taxonomy)
      = f.select :taxonomy_id, Spree::Taxonomy.all.pluck(:name, :id), { include_blank: true }, class: 'select2'

    = f.field_container :user, class: ['form-group'] do
      = f.label :user, Spree.t(:user)
      = f.select :user_id, Spree::User.all.pluck(:email, :id), { include_blank: true }, class: 'select2'

app/views/spree/admin/product_collections/edit.html.slim
- content_for :page_title do
  = link_to Spree.t(:product_collection), admin_product_collections_url
  ' &nbsp;/
  = @product_collection.name

- content_for :page_actions
  = button_link_to 'View Product Collection', product_collections_url(@product_collection), { class: 'btn-default', icon: 'eye-open', target: :_blank }

= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_collection }

= form_for [:admin, @product_collection], html: { multipart: true } do |f|
  fieldset
    = render partial: 'form', locals: { f: f }
    = render partial: 'spree/admin/shared/edit_resource_links'

- if @product_collection_products.present?
  hr

  h3 Products

  table.table
    thead
      tr
        th
          = Spree.t(:name)
        th.actions

    tbody
      - @product_collection_products.each do |product_collection_product|
        - product = product_collection_product.product

        tr id=spree_dom_id(product_collection_product)
          td = product.name

          td.actions.actions-2.text-right
            => link_to_with_icon 'show', 'View', product, class: 'btn btn-default btn-sm', no_text: true, target: '_blank'

            => link_to_edit(product, url: edit_admin_product_path(product), target: '_blank', no_text: true, class: 'edit') if can?(:edit, product)

            = link_to_delete(product_collection_product, url: admin_product_collection_product_path(product_collection_product), no_text: true) if can?(:delete, product_collection_product)

  = paginate @product_collection_products

app/views/spree/admin/product_collections/index.html.slim
- content_for :page_title do
  = plural_resource_name(Spree::ProductCollection)

- if can? :create, Spree::ProductCollection
  - content_for :page_actions do
    = button_link_to Spree.t(:new_product_collection), new_object_url, class: "btn-success", icon: 'add', id: 'admin_new_product_collection_link'

- if @collection.any?
  - content_for :table_filter do
    = search_form_for [:admin, @search] do |f|
      - locals = { f: f }
      .row
        .col-xs-12.col-md-6
          .form-group
            = f.label :name_cont, Spree.t(:name)
            = f.text_field :name_cont, class: "form-control js-quick-search-target js-filterable"

      .form-actions
        = button Spree.t(:search), 'search'

  table.table
    thead
      tr
        th
          = Spree.t(:name)
        th
          = Spree.t(:slug)
        th
          = Spree.t(:taxonomy)
        th.actions
    tbody
      - @collection.each do |product_collection|
        tr id=spree_dom_id(product_collection)
          td
            = product_collection.name
          td
            = product_collection.slug
          td
            = product_collection.taxonomy&.name
          td.actions.actions-2.text-right
            => link_to_with_icon 'show', 'View', product_collections_path(product_collection), class: 'btn btn-default btn-sm', no_text: true, target: '_blank'
            => link_to_edit(product_collection, no_text: true) if can?(:edit, product_collection)
            = link_to_delete(product_collection, no_text: true) if can?(:delete, product_collection)
- else
  .alert.alert-info.no-objects-found
    = Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ProductCollection))
    ' ,
    = link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::ProductCollection)

= paginate @collection

app/views/spree/admin/product_collections/new.html.slim
= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_collection }

- content_for :page_title do
  = link_to Spree.t(:product_collections), admin_product_collections_url
  ' &nbsp;/
  = Spree.t(:new_product_collection)

= form_for [:admin, @product_collection], html: { multipart: true } do |f|
  fieldset
    = render partial: 'form', locals: { f: f }

    .form-actions
      = render partial: 'spree/admin/shared/new_resource_links'